title: Afectados Conciertos Thomas Anders (Modern Talking) España en 2023
description: Documentación y seguimiento del caso de los conciertos cancelados de Modern Talking en España durante 2023
theme: jekyll-theme-cayman

permalink: /:title/

exclude:
  - .github/
  - LICENSE
  - README.md
